### PR TITLE
Anchor Links

### PR DESCRIPTION
**Pull request by Raq-HEE**
## Description
When added to a page, all applicable heading elements in the page between h2 to h6, will have an id assigned if not already present, and anchors will be created for these, where this component has been placed.

Where no id is present on the heading element, one is constructed using the first word of the heading with a counter number postfixed for uniqueness.

Currently no custom css, as default inherited styles are a close match to the visuals provided.

To ignore a heading on the page for the anchor links add data-anchorlinksignore="true" to the heading.

## Checklist

- [ ] Tested against our [testing policy](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/testing.md) (Resolution, Browser & Accessibility)
- [ ] CHANGELOG entry

### CODE REVIEW

**Comment by smanivasag** [comment]
Hi @Raq-HEE - PR looks Great 👍 

Seems like the component creates anchor link for Footer visually hidden heading (`<h2 class="nhsuk-u-visually-hidden" id="support6">Support links</h2>`) as well. Could we not select them if possible ? Thanks!

**Comment by Raq-HEE** [comment]
> 
> 
> Hi @Raq-HEE - PR looks Great 👍
> 
> Seems like the component creates anchor link for Footer visually hidden heading (`<h2 class="nhsuk-u-visually-hidden" id="support6">Support links</h2>`) as well. Could we not select them if possible ? Thanks!

Have updated code to exclude these.

**Comment by Raq-HEE** [comment]
Added fixes in this to PR to issue reported in the platform PR.

**Comment by smanivasag** [comment]
Hi @Raq-HEE - Thanks for the updates. Have added few comments on the platform PR https://github.com/Manifesto-Digital/hee-cms-platform/pull/100. Could you take a look ? Thanks!

**Review by smanivasag — APPROVED** [review]

**Comment by smanivasag** [comment]
Hi @Raq-HEE - Thanks for the fixes, could you resolve the conflict ? Thanks!

**Pull request merged**
