### PR TITLE
NWPS-797 Update "Contact" component

### PR DESCRIPTION
**Pull request by goodvibes**
## Description

https://hee-tis.atlassian.net/browse/NWPS-797

## Checklist

- [ ] Tested against our [testing policy](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/testing.md) (Resolution, Browser & Accessibility)
- [ ] CHANGELOG entry

### CODE REVIEW

**Review by adaMiclos — COMMENTED** [review]
Hi @goodvibes, 

The UI is different compared to the figma: the contact and contact card should have the same styling and display the same fields, the person contact card should display a person's picture or an icon with their initials if the picture doesn't exist, the pronoun, department, organisation, job role have the wrong styling, the 'view more about..' link is missing from the contact component. 

Could you please check if we need to match the figma designs from the ticket? 

Thanks

**Comment by goodvibes** [comment]
@adaMiclos Changes made to align to new figma designs

**Review by Raq-HEE — COMMENTED** [review]
Hi @adaMiclos - it looks more similar to the figma designs now. This may be a non-issue depending on how you are writing the html for contacts on the rhs.. David has grouped them in an unordered list on the right hand side also, and wasn't sure if you're doing the it same way in your ftl?

If not then it's fine as it is, otherwise the <li> will need a width 100% applied to it.

image


cc: @dawntaroni

**Review by adaMiclos — APPROVED** [review]
The UI looks good.

**Pull request merged**
