### PR TITLE
Feature/hee 169 drop down menus

### PR DESCRIPTION
**Pull request by goodvibes**
## Description

https://manifesto.atlassian.net/browse/HEE-169

Adds "lks-header" component, updates views to use this component. Component enables sub-menu's.

## Checklist

- [x] Tested against our [testing policy](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/testing.md) (Resolution, Browser & Accessibility)
- [ ] CHANGELOG entry

### CODE REVIEW

**Comment by smanivasag** [comment]
Hi @goodvibes - Thanks for the PR and sorry for the delayed review. Would like to raise/clarify on the following:

- With top level navigations being shown, when `Menu` button is clicked, it still maintains the (yellow) active state. This is working fine though when the top level navigations is closed using (cross) `Close` button ?
- On Desktop, the top level navigation (yellow) highlight during mouse hover happens during double tap only, was that intentional ?

Thank you!

**Comment by Raq-HEE** [comment]
Hi @goodvibes - looking good, just some things I spotted (which might not be an issue if agreed with design team):

- Acceptance criteria for mobile: _On clicking any of the top level navigation items, the sub level navigation should be animated into view – appearing from the right of the screen and overlaying the top level navigation (if any sub level navigation items exist)_
- _The ‘Menu’ title should be changed for ‘Back to main menu' or ‘Back' for smaller devices_
  - Clicking the "Back" text does not do anything
- On Desktop clicking on multiple sub menu headings keeps them all open. Is this intentional?
- Can we have a HTML example in the Readme, as likely to be referrring to that when integrating with CMS?
- Is it worth copying the attributes table from the NHSUK prototype into the readme with anything additional you've introduced as it's not available in GitHub, unless we checkout and build using npm locally?

Thanks

**Comment by goodvibes** [comment]
@smanivasag I have re-written the script if you would like to review

Regarding the menu buttons staying yellow sometimes, that's because they've received focus and it hasn't changed yet. I could force a blur but technically it's the correct behaviour.

**Comment by smanivasag** [comment]
> @smanivasag I have re-written the script if you would like to review
> 
> Regarding the menu buttons staying yellow sometimes, that's because they've received focus and it hasn't changed yet. I could force a blur but technically it's the correct behaviour.

Thanks @goodvibes. Looks like the following issue still exists and it happens during the click event:

> With top level navigations being shown, when Menu button is clicked, it still maintains the (yellow) active state. This is working fine though when the top level navigations is closed using (cross) Close button ?

Could this be addressed ?

Also, could you confirm if Raq's comments are addressed ? Thanks!

**Comment by smanivasag** [comment]
Hi @goodvibes - As discussed during our call, it will be good to take a look at the following points:

- On desktop, collapse an opened menu when clicked outside (i.e. during an `onBlur`).
- On mobile, get the focus back to `Menu` button when the menu dropdown is closed via cross close button.

Thanks!

**Comment by goodvibes** [comment]
Added submenu close on outside click, and as a bonus the mobile menu will now close on outside click too (and reset any open subs)

**Review by smanivasag — APPROVED** [review]

**Review by Raq-HEE — APPROVED** [review]
Thanks for doing these @goodvibes
Approved

**Pull request merged**
