### PR TITLE
Feature/hee 278 mapping component

### PR DESCRIPTION
**Pull request by goodvibes**
## Description

Adding mapping component as per https://manifesto.atlassian.net/browse/HEE-278

## Checklist

- [x ] Tested against our [testing policy](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/testing.md) (Resolution, Browser & Accessibility)

### CODE REVIEW

**Comment by smanivasag** [comment]
Hi @goodvibes - Thanks for the PR. The AC described in https://manifesto.atlassian.net/browse/HEE-278?focusedCommentId=94382 indicates that the map element of the component should be invisible in mobile view:

> Given a user was using a mobile, when the user views the component, then only the headline, then the map element of the component will not be visible.

But, the prototype currently seems to render the map in mobile view as well. Could you fix this ? Thanks!

**Comment by smanivasag** [comment]
Hi @goodvibes - Thanks for the latest commit e066169a62789864130b1f9f7fbb07f62b928e99. I could see that the map is now being hidden in mobile view.

I could see lot of top and left padding on the component (in mobile view). Could you check if this can be reduced ? Thanks!

**Comment by goodvibes** [comment]
@smanivasag I have gone over the last few details with Will and I think this is ready for deploy if you would like to review

**Comment by smanivasag** [comment]
> @smanivasag I have gone over the last few details with Will and I think this is ready for deploy if you would like to review

Have you got a chance to look into the top and left padding concern I have raised in https://github.com/Manifesto-Digital/hee-prototypes/pull/20#issuecomment-891042059 ? thanks!

**Comment by smanivasag** [comment]
Hi @goodvibes - As discussed during our call, it would good to reduce left padding for the links in mobile view. Thanks!

**Review by smanivasag — APPROVED** [review]

**Pull request merged**
