### PR TITLE
Media component

### PR DESCRIPTION
**Pull request by goodvibes**
Branch: feature/HEE-203-Video-Component

https://manifesto.atlassian.net/browse/HEE-203 AND https://manifesto.atlassian.net/browse/HEE-204

Media component that supports youtube, vimeo and anchor.fm links.

## Checklist

- [ x] Tested against our [testing policy](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/testing.md) (Resolution, Browser & Accessibility)
- [ ] CHANGELOG entry

### CODE REVIEW

**Comment by Raq-HEE** [comment]
Hi David - Thanks for this PR, it's looking good. 

I wasn't sure if I was looking at the correct figma designs, but spotted a couple of minor differences
image

- The heading doesn't have a white background
- View transcript styling different (although, your version looks fine to me, maybe worth checking with Will)
- Last review / Next review bits missing.

**Comment by Raq-HEE** [comment]
Horizontal scroll appears around below 560px. Maybe allow the video to scale down a bit more to allow for smaller screens.
image

**Comment by Raq-HEE** [comment]
Where there is no metadata to show beneath the player, should we hide the white bit at the bottom?
image

**Comment by Raq-HEE** [comment]
handle no-js for the transcript.
image
Is the transcript pulled down from Youtube? Maybe check with Will on whether he wants the entire transcript to show, or not when there's no js.

**Comment by goodvibes** [comment]
@Raq-HEE ready for review again

**Review by Raq-HEE — APPROVED** [review]
Hey @David - thanks for doing these. It looks really good. Approved.

**Pull request merged**
